### ISSUE TITLE
[BUG] Breaks shaders, degrades performance of some shaders and doesn't load shaders :O

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#1013]
**Describe the bug**
This started with the Photon shaders. They failed to load ~80% of the the time and when they did, performance dropped from 130fps to 20fps. My game crashed with Photon a few times. Complementary got affected soon afterwards. (see screenshots below)

Log: https://mclo.gs/cVi5SRO (ignore resource pack spam lol) Crash: https://mclo.gs/w4OzQ2R
Latest release of Physics Mod has the same issue: https://mclo.gs/Vq1cQOh

**Screenshots**
![2024-12-06_16 30 05](https://github.com/user-attachments/assets/db503f37-3b6a-44bc-b40a-a57311b5fdc1)

Minecraft Version: <1.21.1>
Physics Mod Version: <v172 NeoForge 1.21.1>

Could this be a config issue?

**Comment by VOLKOUL** [comment]
I think part of it was config related. I deleted the old config file and reconfigured the mod. Performance seems to be a lot better now. ~~I will close the issue for now and try and do some more observations.~~

**Comment by VOLKOUL** [comment]
So the Photon shader lag SEEMS to be gone, but Complementary 4.7.2 (not to be confused with the latest release) still behaves like in the screenshot attached. There are also noticeable fps drops in other shaders.

**Comment by haubna** [comment]
You have a lot of mods installed, can you reproduce this issue with only iris + sodium + physics mod?

**Comment by VOLKOUL** [comment]
~~No, I can't reproduce this with a minimal set of mods :D it seems to be a mod incompatibility.~~ I am in the process of thanossnapping my modpack to determine the cause. I thought I had found the problematic mod at first but turns out the issue doesn't happen every time and I missed it. I will give an update soon.

**Comment by haubna** [comment]
Much appreciated, thanks!

**Comment by VOLKOUL** [comment]
Sooo forget about me saying that I can't reproduce this with just Physics Mod, Sodium and Iris because unfortunately I can. The issue seems to be caused by Physics Mod (and Iris, duh). Since the bug doesn't happen every time I initially thought that there was another mod causing this, sorry for the misinformation. I made a fresh installation with just the three mods mentioned above and removing Physics Mod makes the issue disappear (AT LEAST FROM WHAT I'VE OBSERVED, I HOPE I'M NOT WRONG AGAIN AAA) Here's the clean Log: https://mclo.gs/ioB1PoI I also asked about this in the Iris discord before making the bug report here and they said that it was caused by Physics Mod, I just wasn't sure and thought that doing some testing wouldn't do bad. I will upload a video demonstrating the issue soon.

**Comment by haubna** [comment]
It seems like some shaders are not properly linking on your system. Even ones that the physics mod doesn't even touch. I don't know why that happens though. You could try newer versions of Minecraft (1.21.4) and see if that problem still persists there. Oh and could you use the Complementary shaderpack for testing? Photon isn't officially supported by the physics mod so there might be issues due to that.

```
[17Nov2024 16:14:08.802] [Render thread/WARN] [com.mojang.blaze3d.shaders.ProgramManager/]: Error encountered when linking program containing VS entities_alpha and FS entities_alpha. Log output:
4430 | [17Nov2024 16:14:08.803] [Render thread/WARN] [com.mojang.blaze3d.shaders.ProgramManager/]: Link info
4431 | ---------
4432 | error: interpolation modifier mismatch for varying parameter (named tbn) between shader stages
4433
```

**Comment by haubna** [comment]
Ok from my testing it appears to be a problem with the Photon shaderpack. In 1.21.4 however it simply doesn't load the shaderpack and switches to the default vanilla one. I will look further into it.

**Comment by haubna** [comment]
I've fixed the Photon shaderpack to now load with the physics mod in 1.21.4, if you want ocean physics support you can ask the shaderpack creator to implement it. All the information about it can be found here: https://github.com/haubna/PhysicsMod

**Comment by VOLKOUL** [comment]
Thank you! Any possibility that 1.21.1 gets the fix too?

**Comment by VOLKOUL** [comment]
Hey, just wanted to let you know that it is still an issue on 1.21.1

![Image](https://github.com/user-attachments/assets/9821e3c5-8053-4acc-a2b7-c3605267d7c9)

**Comment by VOLKOUL** [comment]
I also got the Iris error message in chat after disabling photon and turning it back on.
