### ISSUE TITLE
Game CRASHES launching [Replay] mode with Flashback + Physics Mod

### ISSUE THREAD

**Issue by mharrywhiz** [haubna/PhysicsMod#1138]
**Describe the bug**
Every time I create a recording with the 'Flashback' mod, and then load into the 'Replay' mode to view and edit footage, the game crashes. I've removed every other mod apart from 'Flashback' & 'Physics' and even created a fresh instance with just those two mods installed, but the problem persists.

**To Reproduce**
Launch [Replay] mode with the Flashback mod

**Screenshots**

Minecraft Version: 1.21.1
Physics Mod Version: physics-mod-pro-v172j-fabric-1.21.1

**Comment by haubna** [comment]
I've uploaded v172k which should fix this issue, thanks for the report!

**Comment by arthurhelk-jpg** [comment]
i am still facing the exact same problem with v172k.  my game still crashes everytime i try and open a recording from the flashback mod. can u help?

**Comment by haubna** [comment]
A crash log will help

**Comment by Foxil9** [comment]
Man I am going to help because I want this issue gone. Here is a crash log:
https://mclo.gs/XoEN54D

**Comment by bravekwik13-dot** [comment]
it still happens to me
