### ISSUE TITLE
Inconsistent lighting on physics objects with Blue's Dynamic Lights mod for Forge

### ISSUE THREAD

**Issue by Oranamous** [haubna/PhysicsMod#540]
**Describe the bug**
Light casted by held items with BDL (Blue's Dynamic Lights) doesn't get applied due to BDL's usage of core shaders to apply the custom light, and Physics Mod's usage of custom core shaders in the jar for physics objects. I was unable to patch Physics Mod's shaders using a resource pack, and I'm not sure if that would've helped anyway due to BDL's usage of custom uniforms. After further investigation I found that Physics Mod only accepts shader resources from inside it's own jar. I would prefer not to have to edit the Physics Mod's shaders directly in the jar each time I update the mod, I'm not experienced enough or sure if it's even possible to create a separate mod that patches Physics Mod to have compatibility with BDL. 🤔

**To Reproduce**
Install both Physics Mod and [Blue's Dynamic Lights](https://www.curseforge.com/minecraft/mc-mods/blues-dynamic-lights) on forge and open the game. Go to a dark area and place some blocks, hold a torch or glowstone and destroy the blocks you placed to get some physics objects to appear. Observe the dark lighting on the physics objects, while the surrounding area is lit by the held item.

**Screenshots**
Normal behavior with block lights:
![2023-01-18_22 04 48](https://user-images.githubusercontent.com/89707570/213352845-af0313e0-dce9-4c29-9f1e-19c298b5fe1a.png)
Inconsistent behavior with held lights:
![2023-01-18_22 05 01](https://user-images.githubusercontent.com/89707570/213352860-1faf79af-c21f-4ce7-869c-a1d64c93d743.png)

Minecraft Version: Tested on 1.19.2 and 1.19.3, likely applies to all versions where both mods are present
Physics Mod Version: 2.9.4, issue still present in 2.9.7

**Comment by haubna** [comment]
This will likely never be supported since shaders already do this without destroying my lighting improvements.

**Comment by Oranamous** [comment]
Understandable, I figured I'd report it just in case. Would it be possible for me to fix this myself, and would you be alright with me editing a local copy of the mod in order to do so? I won't attempt to crack a copy of the pro version, I just want to fix this compatibility issue as it breaks my immersion.

**Comment by haubna** [comment]
Oh yeah for sure, go ahead!

**Comment by haubna** [comment]
Fixed in V112 (will come to lite version soon too)

**Comment by Oranamous** [comment]
Issue still occurs after checking that both mods are up-to-date, despite curseforge changelogs stating that this is fixed 🤔

![image](https://user-images.githubusercontent.com/89707570/215637099-7c31c71d-7196-4143-89db-184d5b168b3c.png)

**Comment by Oranamous** [comment]
It appears this is fixed for some users but not others. A friend of mine showed it working, but for me it doesn't, and we were both using the same modpack and the same settings. My guess is it's a GPU-specific problem.
