### ISSUE TITLE
Ocean physics causes issues underwater

### ISSUE THREAD

**Issue by gitguette** [haubna/PhysicsMod#754]
**Describe the bug**
If underwater and ocean physics are enabled, blocks like stairs and and slabs will appear to not be waterlogged.

**To Reproduce**
- Enable ocean physics
- Go underwater
- Find a structure that uses downwards facing stairs.

**Screenshots**
![2023-10-01_11 09 54](https://github.com/haubna/PhysicsMod/assets/109386903/8190f833-85ac-4d3c-a958-18b11f3916a6)

Minecraft Version: 1.20.1(Forge 47.1.3)
Physics Mod Version: 3.0.8 Pro

**Comment by haubna** [comment]
I've just uploaded Pro v161 which should fix this issue. Thanks for the report!

**Comment by gitguette** [comment]
seems to still happen under blocks

ocean physics enabled:
![2023-10-02_17 47 53](https://github.com/haubna/PhysicsMod/assets/109386903/069e1e25-22a2-4048-a7d5-a307f78088f2)

ocean physics disabled:
![2023-10-02_17 48 21](https://github.com/haubna/PhysicsMod/assets/109386903/0fc0b3c8-5b26-403a-9034-f6592b80914e)
